---
version: '3.7'
services:
  security:
    image: wluisaraujo/openldap
    container_name: openldap
    dns_search: ldap.dexter.com.br
    restart: always
    network_mode: "host"
    networks:
      app_net:
        ipv4_address: 172.16.238.10
    dns:
      - 127.0.0.1
      - 8.8.8.8
    ports:
      - "389/tcp:389/tcp"
      - "636/tcp:636/udp"
    expose:
      - "389/udp"
      - "636/tcp"
    extra_hosts:
      - "ns1.dexter.com.br:172.16.238.10"  
      - "ldap.dexter.com.br:172.16.238.10"  
...
